ExDataPlot1Data1 <- read.table(file='household_power_consumption.txt', header=FALSE,col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),sep=";",dec=".", colClasses="character",skip=66637,nrow=2881)
ExDataPlot1Data1$Date<-as.Date(ExDataPlot1Data1$Date,format='%d/%m/%Y')
ExDataPlot1Data1$Time<-format(ExDataPlot1Data1$Time,format='%H:%M:%S')
ExDataPlot1Data1$Global_active_power<-as.numeric(ExDataPlot1Data1$Global_active_power)
ExDataPlot1Data1$Global_reactive_power<-as.numeric(ExDataPlot1Data1$Global_reactive_power)
ExDataPlot1Data1$Voltage<-as.numeric(ExDataPlot1Data1$Voltage)
ExDataPlot1Data1$Global_intensity<-as.numeric(ExDataPlot1Data1$Global_intensity)
ExDataPlot1Data1$Sub_metering_1<-as.numeric(ExDataPlot1Data1$Sub_metering_1)
ExDataPlot1Data1$Sub_metering_2<-as.numeric(ExDataPlot1Data1$Sub_metering_2)
ExDataPlot1Data1$Sub_metering_3<-as.numeric(ExDataPlot1Data1$Sub_metering_3)

png(file="plot1.png")
with(ExDataPlot1Data1[(ExDataPlot1Data1$Date == as.Date("2007-02-01")) | (ExDataPlot1Data1$Date == as.Date("2007-02-02")),], hist(ExDataPlot1Data1$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)"))
dev.off()
